# devgagan
# Note if you are trying to deploy on vps then directly fill values in ("")

from os import getenv

API_ID = int(getenv("API_ID", "29171167"))
API_HASH = getenv("API_HASH", "7ea2149629e445936619f06a3c0dc716")
BOT_TOKEN = getenv("BOT_TOKEN", "7507845986:AAGZbQv9-eGEUCgFk0j3ccGDwznPemkK8R8")
OWNER_ID = list(map(int, getenv("OWNER_ID", "7251898668").split()))
MONGO_DB = getenv("MONGO_DB", "mongodb+srv://save:save@cluster0.ftlr8.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
LOG_GROUP = getenv("LOG_GROUP", "-1002250141502")
CHANNEL_ID = int(getenv("CHANNEL_ID", "-1002198396079"))
FREEMIUM_LIMIT = int(getenv("FREEMIUM_LIMIT", "50"))
PREMIUM_LIMIT = int(getenv("PREMIUM_LIMIT", "500"))
WEBSITE_URL = getenv("WEBSITE_URL", "")
AD_API = getenv("AD_API", "")
STRING = getenv("STRING", None)
YT_COOKIES = getenv("YT_COOKIES", # Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
#HttpOnly_.youtube.com	TRUE	/	TRUE	1753109339	VISITOR_PRIVACY_METADATA	CgJJThIEGgAgbQ%3D%3D
.youtube.com	TRUE	/	FALSE	1736658858	ST-mvdfpw	csn=1Es0QhLO1JZGERmL&itct=CC8Q_FoYASITCLal1K6274oDFdH_OAYdaqElnjIGc2VhcmNoUgFomgEDEPQk
.youtube.com	TRUE	/	FALSE	1736658859	ST-4sz0zp	csn=1Es0QhLO1JZGERmL&itct=CC4Q_FoYAiITCLal1K6274oDFdH_OAYdaqElnjIGc2VhcmNoUgFomgEDEPQk
#HttpOnly_.youtube.com	TRUE	/	TRUE	1737559137	GPS	1
#HttpOnly_.youtube.com	TRUE	/	TRUE	1737643748	YSC	qmMjd0TQkEE
.youtube.com	TRUE	/	FALSE	1736658863	ST-69bqjw	csn=1Es0QhLO1JZGERmL&itct=CCsQ_FoYBSITCLal1K6274oDFdH_OAYdaqElnjIGc2VhcmNoUgFomgEDEPQk
#HttpOnly_.youtube.com	TRUE	/	TRUE	1753109337	__Secure-ROLLOUT_TOKEN	CKCWl4S8_6HAzwEQ6pj-qrbvigMYxPW1v8mJiwM%3D
.youtube.com	TRUE	/	TRUE	1772117339	PREF	f6=40000000&tz=Asia.Kolkata&f7=100&f4=4000000
.youtube.com	TRUE	/	FALSE	1736665129	ST-148bo7q	csn=rFARhKezTO6-xT5c&itct=CFkQ_FoiEwiBuZ7cze-KAxV6RfUFHXN_IXYyCmctaGlnaC1yZWNaD0ZFd2hhdF90b193YXRjaJoBBhCOHhieAQ%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1753109339	VISITOR_INFO1_LIVE	VO5y8dNTBr8)
INSTA_COOKIES = getenv("INSTA_COOKIES", None)
